import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import Navbar from "@/components/Navbar";
import "remixicon/fonts/remixicon.css";
import "./globals.css";

const kanit = Kanit({
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-kanit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Muntasir",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className} antialiased bg-custom-background`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
